"""add temporary column to pantry_items

Revision ID: a7f24305f8bf
Revises: 
Create Date: 2025-05-09 16:17:09.304760

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a7f24305f8bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1) add column WITH a server_default so existing rows are back-filled FALSE
    op.add_column(
        'pantry_items',
        sa.Column(
            'temporary',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    # 2) immediately remove that default so your model’s default (False) takes over
    op.alter_column(
        'pantry_items',
        'temporary',
        existing_type=sa.Boolean(),
        server_default=None,
    )

    # the rest of your autogenerated non-null/index tweaks:
    op.alter_column('pantry_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pantry_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pantry_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_user_settings_user_id', table_name='user_settings')
    op.create_index(op.f('ix_user_settings_id'),
                    'user_settings', ['id'], unique=False)


def downgrade() -> None:
    # undo index changes
    op.drop_index(op.f('ix_user_settings_id'),
                  table_name='user_settings')
    op.create_index('idx_user_settings_user_id',
                    'user_settings', ['user_id'], unique=False)

    # revert nullability
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pantry_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pantry_items', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pantry_items', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # drop the column
    op.drop_column('pantry_items', 'temporary')
